DROP TABLE IF EXISTS `pybot_map`;
CREATE TABLE `pybot_map` (
  `name_english` varchar(11) NOT NULL,
  `name_japanese` varchar(100) NOT NULL,
  `nation_type` tinyint(2) unsigned NOT NULL,
  `map_type` tinyint(2) unsigned NOT NULL,
  `fever_flag` tinyint(1) unsigned NOT NULL,
  PRIMARY KEY (`name_english`)
) ENGINE=MyISAM;

REPLACE INTO `pybot_map` VALUES('alb_ship', 'アルベルタ船舶の中', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('alb2trea', '沈没船の付近の島', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('alberta', '港の都市アルベルタ', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('alberta_in', '港の都市アルベルタ 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('alde_dun01', 'アルデバラン時計塔地下 1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('alde_dun02', 'アルデバラン時計塔地下 2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('alde_dun03', 'アルデバラン時計塔地下 3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('alde_dun04', 'アルデバラン時計塔地下 4F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('aldeba_in', '国境都市アルデバラン 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('aldebaran', '国境都市アルデバラン', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('anthell01', '蟻地獄ダンジョン B1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('anthell02', '蟻地獄ダンジョン B2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('arena_room', 'アリーナ待機室', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('c_tower1', 'アルデバラン時計塔地上 1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('c_tower2', 'アルデバラン時計塔地上 2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('c_tower3', 'アルデバラン時計塔地上 3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('c_tower4', 'アルデバラン時計塔地上 4F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('force_1-1', 'タイムアタックモード 1-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_1-2', 'タイムアタックモード 1-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_1-3', 'タイムアタックモード 1-3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_2-1', 'タイムアタックモード 2-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_2-2', 'タイムアタックモード 2-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_2-3', 'タイムアタックモード 2-3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_3-1', 'タイムアタックモード 3-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_3-2', 'タイムアタックモード 3-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_3-3', 'タイムアタックモード 3-3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('gef_dun00', 'ゲフェン地下ダンジョン B1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gef_dun01', 'ゲフェン地下ダンジョン B2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gef_dun02', 'ゲフェン地下ダンジョン B3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gef_dun03', 'ゲフェン地下ダンジョン B4F', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('gef_fild00', 'ゲフェンフィールド 00', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild01', 'ゲフェンフィールド 01', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild02', 'ゲフェンフィールド 02', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild03', 'ゲフェンフィールド 03', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild04', 'ゲフェンフィールド 04', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild05', 'ゲフェンフィールド 05', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild06', 'ゲフェンフィールド 06', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild07', 'ゲフェンフィールド 07', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild08', 'ゲフェンフィールド 08', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild09', 'ゲフェンフィールド 09', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild10', 'ゲフェンフィールド 10', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild11', 'ゲフェンフィールド 11', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild12', 'ゲフェンフィールド 12（コードの森）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild13', 'ゲフェンフィールド 13（ブリトニア）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_fild14', 'ゲフェンフィールド 14（オーク西の村）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('gef_tower', 'ゲフェン中央塔', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('geffen', '魔法の都市ゲフェン', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('geffen_in', '魔法の都市ゲフェン 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('gl_cas01', 'グラストヘイム 古城1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_cas02', 'グラストヘイム 古城2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_church', 'グラストヘイム 修道院', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_chyard', 'グラストヘイム カタコンベ', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_dun01', 'グラストヘイム 最下層地下洞窟01', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_dun02', 'グラストヘイム 最下層地下洞窟02', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_in01', 'グラストヘイム 室内01', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_knt01', 'グラストヘイム 騎士団内01', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_knt02', 'グラストヘイム 騎士団内02', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_prison', 'グラストヘイム 地下監獄00', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_prison1', 'グラストヘイム 地下監獄01', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_sew01', 'グラストヘイム地下水路 01', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_sew02', 'グラストヘイム地下水路 02', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_sew03', 'グラストヘイム地下水路 03', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_sew04', 'グラストヘイム地下水路 04', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gl_step', 'グラストヘイム 階段ダンジョン', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('glast_01', 'グラストヘイム 古城', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('hunter_1-1', 'ハンター転職所 1-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('hunter_2-1', 'ハンター転職所 2-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('hunter_3-1', 'ハンター転職所 3-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('in_hunter', '調査用マップ2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('in_moc_16', 'アサシンギルド', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('in_orcs01', 'オーク村の室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('in_sphinx1', 'スフィンクスダンジョン B1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('in_sphinx2', 'スフィンクスダンジョン B2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('in_sphinx3', 'スフィンクスダンジョン B3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('in_sphinx4', 'スフィンクスダンジョン B4F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('in_sphinx5', 'スフィンクスダンジョン B5F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('iz_dun00', 'イズルード海底洞窟 1層', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('iz_dun01', 'イズルード海底洞窟 2層', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('iz_dun02', 'イズルード海底洞窟 3層', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('iz_dun03', 'イズルード海底洞窟 4層', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('iz_dun04', 'イズルード海底神殿', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('job_sword1', '？', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('izlu2dun', 'バイラン島', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('izlude', '衛星都市イズルード', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('izlude_in', '衛星都市イズルード 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_thief1', 'シブのキノコ農場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('knight_1-1', 'ナイト転職所 1-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('knight_2-1', 'ナイト転職所 2-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('knight_3-1', 'ナイト転職所 3-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('mjo_dun01', 'ミョルニール廃鉱 B1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('mjo_dun02', 'ミョルニール廃鉱 B2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('mjo_dun03', 'ミョルニール廃鉱 B3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_01', 'ミョルニール山脈 01', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_02', 'ミョルニール山脈 02', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_03', 'ミョルニール山脈 03', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_04', 'ミョルニール山脈 04', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_05', 'ミョルニール山脈 05', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_06', 'ミョルニール山脈 06', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_07', 'ミョルニール山脈 07', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_08', 'ミョルニール山脈 08', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_09', 'ミョルニール山脈 09', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_10', 'ミョルニール山脈 10', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_11', 'ミョルニール山脈 11', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('mjolnir_12', 'ミョルニール山脈 12', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_castle', 'モロク城内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild01', 'ソグラト砂漠 01', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild02', 'ソグラト砂漠 02', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild03', 'ソグラト砂漠 03', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild04', 'ソグラト砂漠 04', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild05', 'ソグラト砂漠 05', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild06', 'ソグラト砂漠 06', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild07', 'ソグラト砂漠 07', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild08', 'ソグラト砂漠 08', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild09', 'ソグラト砂漠 09', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild10', 'ソグラト砂漠 10', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild11', 'ソグラト砂漠 11', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild12', 'ソグラト砂漠 12', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild13', 'ソグラト砂漠 13', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild14', 'ソグラト砂漠 14', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild15', 'ソグラト砂漠 15', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild16', 'ソグラト砂漠 16', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild17', 'ソグラト砂漠 17', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild18', 'ソグラト砂漠 18', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild19', 'ソグラト砂漠 19', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_pryd01', 'ピラミッドダンジョン 1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('moc_pryd02', 'ピラミッドダンジョン 2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('moc_pryd03', 'ピラミッドダンジョン 3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('moc_pryd04', 'ピラミッドダンジョン 4F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('moc_pryd05', 'ピラミッドダンジョン B2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('moc_pryd06', 'ピラミッドダンジョン B3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('moc_prydb1', 'シーフギルド', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_ruins', 'モロク - ピラミッド周辺', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('monk_in', '聖カピトーリナ修道院内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('morocc', '砂漠の都市モロク', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('morocc_in', '砂漠の都市モロク 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_1-1', '初心者修練場 1-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_1-2', '初心者修練場 1-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_1-3', '初心者修練場 1-3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_1-4', '初心者修練場 1-4', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_2-1', '初心者修練場 2-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_2-2', '初心者修練場 2-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_2-3', '初心者修練場 2-3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_2-4', '初心者修練場 2-4', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_3-1', '初心者修練場 3-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_3-2', '初心者修練場 3-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_3-3', '初心者修練場 3-3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_3-4', '初心者修練場 3-4', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_4-1', '初心者修練場 4-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_4-2', '初心者修練場 4-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_4-3', '初心者修練場 4-3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_4-4', '初心者修練場 4-4', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_5-1', '初心者修練場 5-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_5-2', '初心者修練場 5-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_5-3', '初心者修練場 5-3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_5-4', '初心者修練場 5-4', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('orcsdun01', 'オーク地下洞窟 01', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('orcsdun02', 'オーク地下洞窟 02', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('ordeal_1-1', 'バトルオディールモード 1-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('ordeal_1-2', 'バトルオディールモード 1-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('ordeal_2-1', 'バトルオディールモード 2-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('ordeal_2-2', 'バトルオディールモード 2-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('ordeal_3-1', 'バトルオディールモード 3-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('ordeal_3-2', 'バトルオディールモード 3-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pay_arche', 'フェイヨン弓手村', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('pay_dun00', 'フェイヨン地下洞窟 B1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('pay_dun01', 'フェイヨン地下洞窟 B2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('pay_dun02', 'フェイヨン地下洞窟 B3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('pay_dun03', 'フェイヨン地下洞窟 B4F（地下寺院）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('pay_dun04', 'フェイヨン地下洞窟 B5F（地下寺院）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild01', 'フェイヨン迷いの森 01', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild02', 'フェイヨン迷いの森 02', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild03', 'フェイヨン迷いの森 03', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild04', 'フェイヨン迷いの森 04', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild05', 'フェイヨン迷いの森 05', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pay_fild06', 'フェイヨン迷いの森 06', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild07', 'フェイヨン迷いの森 07', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild08', 'フェイヨン迷いの森 08', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild09', 'フェイヨン迷いの森 09', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild10', 'フェイヨン迷いの森 10', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('pay_fild11', 'フェイヨン迷いの森 11', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('payon', '山岳の都市フェイヨン', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('payon_in01', '山岳の都市フェイヨン 室内01', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('payon_in02', '山岳の都市フェイヨン 室内02', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('priest_1-1', 'プリースト転職所 1-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('priest_2-1', 'プリースト転職所 2-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('priest_3-1', 'プリースト転職所 3-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('prontera', 'ルーンミッドガッツ王国の首都プロンテラ', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('prt_are_in', 'アリーナ待機室', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_are01', 'アリーナ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_room', '大演習場　ロビー', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_castle', 'プロンテラ城内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_church', 'プロンテラ聖堂内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_fild00', 'プロンテラフィールド 00', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild01', 'プロンテラフィールド 01', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild02', 'プロンテラフィールド 02', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild03', 'プロンテラフィールド 03', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild04', 'プロンテラフィールド 04', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild05', 'プロンテラフィールド 05', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild06', 'プロンテラフィールド 06', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild07', 'プロンテラフィールド 07', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild08', 'プロンテラフィールド 08', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild09', 'プロンテラフィールド 09', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild10', 'プロンテラフィールド 10', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_fild11', 'プロンテラフィールド 11', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('prt_in', '首都プロンテラ 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_maze01', '迷宮の森 01', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('prt_maze02', '迷宮の森 02', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('prt_maze03', '迷宮の森 03', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('prt_monk', '聖カピトーリナ修道院', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('prt_sewb1', 'プロンテラ地下水路 B1F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('prt_sewb2', 'プロンテラ地下水路 B2F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('prt_sewb3', 'プロンテラ地下水路 B3F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('prt_sewb4', 'プロンテラ地下水路 B4F', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('pvp_2vs2', 'PvP : イベントホール', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_c_room', 'PvP : 控え室', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_1-1', 'PvP : 南北戦争', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_1-2', 'PvP : ロックオン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_1-3', 'PvP : フォールーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_1-4', 'PvP : アンダークロス', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_1-5', 'PvP : ザナクルーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_2-1', 'PvP : 南北戦争', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_2-2', 'PvP : ロックオン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_2-3', 'PvP : フォールーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_2-4', 'PvP : アンダークロス', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_2-5', 'PvP : ザナクルーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_3-1', 'PvP : 南北戦争', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_3-2', 'PvP : ロックオン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_3-3', 'PvP : フォールーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_3-4', 'PvP : アンダークロス', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_3-5', 'PvP : ザナクルーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_4-1', 'PvP : 南北戦争', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_4-2', 'PvP : ロックオン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_4-3', 'PvP : フォールーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_4-4', 'PvP : アンダークロス', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_4-5', 'PvP : ザナクルーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_5-1', 'PvP : 南北戦争', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_5-2', 'PvP : ロックオン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_5-3', 'PvP : フォールーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_5-4', 'PvP : アンダークロス', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_5-5', 'PvP : ザナクルーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_6-1', 'PvP : 南北戦争', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_6-2', 'PvP : ロックオン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_6-3', 'PvP : フォールーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_6-4', 'PvP : アンダークロス', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_6-5', 'PvP : ザナクルーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_7-1', 'PvP : 南北戦争', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_7-2', 'PvP : ロックオン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_7-3', 'PvP : フォールーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_7-4', 'PvP : アンダークロス', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_7-5', 'PvP : ザナクルーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_8-1', 'PvP : 南北戦争', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_8-2', 'PvP : ロックオン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_8-3', 'PvP : フォールーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_8-4', 'PvP : アンダークロス', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_8-5', 'PvP : ザナクルーム', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_n_room', 'PvP : ナイトメアモード控え室', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_1-1', 'PvP : プロンテラ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_1-2', 'PvP : イズルード', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_1-3', 'PvP : フェイヨン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_1-4', 'PvP : アルベルタ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_1-5', 'PvP : モロク', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_2-1', 'PvP : プロンテラ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_2-2', 'PvP : イズルード', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_2-3', 'PvP : フェイヨン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_2-4', 'PvP : アルベルタ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_2-5', 'PvP : モロク', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_3-1', 'PvP : プロンテラ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_3-2', 'PvP : イズルード', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_3-3', 'PvP : フェイヨン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_3-4', 'PvP : アルベルタ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_3-5', 'PvP : モロク', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_4-1', 'PvP : プロンテラ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_4-2', 'PvP : イズルード', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_4-3', 'PvP : フェイヨン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_4-4', 'PvP : アルベルタ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_4-5', 'PvP : モロク', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_5-1', 'PvP : プロンテラ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_5-2', 'PvP : イズルード', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_5-3', 'PvP : フェイヨン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_5-4', 'PvP : アルベルタ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_5-5', 'PvP : モロク', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_6-1', 'PvP : プロンテラ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_6-2', 'PvP : イズルード', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_6-3', 'PvP : フェイヨン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_6-4', 'PvP : アルベルタ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_6-5', 'PvP : モロク', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_7-1', 'PvP : プロンテラ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_7-2', 'PvP : イズルード', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_7-3', 'PvP : フェイヨン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_7-4', 'PvP : アルベルタ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_7-5', 'PvP : モロク', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_8-1', 'PvP : プロンテラ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_8-2', 'PvP : イズルード', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_8-3', 'PvP : フェイヨン', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_8-4', 'PvP : アルベルタ', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_8-5', 'PvP : モロク', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pvp_y_room', 'PvP : ヨーヨーモード控え室', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('sword_1-1', '剣士転職所 1-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('sword_2-1', '剣士転職所 2-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('sword_3-1', '剣士転職所 3-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('treasure01', '沈没船 1層', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('treasure02', '沈没船 2層', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('wizard_1-1', 'ウィザード転職所 1-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('wizard_2-1', 'ウィザード転職所 2-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('wizard_3-1', 'ウィザード転職所 3-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('xmas', '雪の街ルティエ', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('xmas_dun01', 'おもちゃ工場ダンジョン 01（倉庫）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('xmas_dun02', 'おもちゃ工場ダンジョン 02（分類所）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('xmas_fild01', 'ルティエフィールド 01', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('xmas_in', 'ルティエ 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('beach_dun', 'コモドダンジョン 01（西洞窟カル）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('beach_dun2', 'コモドダンジョン 02（北洞窟ルワンダ）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('beach_dun3', 'コモドダンジョン 03（東洞窟マオ）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('cmd_fild01', 'コモドフィールド 01（パプチカ森）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('cmd_fild02', 'コモドフィールド 02（ココモビーチ）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('cmd_fild03', 'コモドフィールド 03（ジナイ沼）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('cmd_fild04', 'コモドフィールド 04（ココモビーチ）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('cmd_fild05', 'コモドフィールド 05（パプチカ森境）', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('cmd_fild06', 'コモドフィールド 06（サンダルマン要塞西）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('cmd_fild07', 'コモドフィールド 07（ファロス燈台島）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('cmd_fild08', 'コモドフィールド 08（サンダルマン要塞東）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('cmd_fild09', 'コモドフィールド 09（サンダルマン要塞南）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('cmd_in01', 'コモド 室内01', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('cmd_in02', 'コモド 室内02', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('comodo', '幻想の島コモド', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('quiz_00', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('quiz_01', 'クイズ会場 01', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('g_room1-1', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('g_room1-2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('g_room1-3', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('g_room2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('tur_dun01', 'タートルアイランド', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('tur_dun02', 'タートルアイランドダンジョン 01', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('tur_dun03', 'タートルアイランドダンジョン 02（陽居村）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('tur_dun04', 'タートルアイランドダンジョン 03（久陽宮）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('tur_dun05', '地下湿地帯 05', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('tur_dun06', '地下湿地帯 06', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('alde_gld', 'アルデバラン衛星都市ルイーナ', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('aldeg_cas01', 'ルイーナ 砦1', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('aldeg_cas02', 'ルイーナ 砦2', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('aldeg_cas03', 'ルイーナ 砦3', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('aldeg_cas04', 'ルイーナ 砦4', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('aldeg_cas05', 'ルイーナ 砦5', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gefg_cas01', 'ブリトニア 砦1', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gefg_cas02', 'ブリトニア 砦2', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gefg_cas03', 'ブリトニア 砦3', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gefg_cas04', 'ブリトニア 砦4', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gefg_cas05', 'ブリトニア 砦5', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gld_dun01', 'ギルドダンジョン フェイヨン', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gld_dun02', 'ギルドダンジョン アルデバラン', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gld_dun03', 'ギルドダンジョン プロンテラ', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('gld_dun04', 'ギルドダンジョン ゲフェン', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('guild_room', 'ギルドコロシアム 控室', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs1', 'ギルドコロシアム 1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs2', 'ギルドコロシアム 2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs3', 'ギルドコロシアム 3', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs4', 'ギルドコロシアム 4', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs5', '不思議な空間前', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs1-1', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs1-2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs1-3', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs1-4', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs2-1', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('guild_vs2-2', 'ギルドコロシアム 2-2', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_hunte', 'ハンター転職試験場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_knt', 'ナイト転職試験場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_prist', 'プリースト転職試験場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_wiz', 'ウィザード転職試験場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('pay_gld', 'チュンリム湖', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('payg_cas01', 'チュンリム湖 砦1', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('payg_cas02', 'チュンリム湖 砦2', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('payg_cas03', 'チュンリム湖 砦3', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('payg_cas04', 'チュンリム湖 砦4', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('payg_cas05', 'チュンリム湖 砦5', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('prt_gld', 'ヴァルキリーレルム', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('prtg_cas01', 'ヴァルキリーレルム 砦1', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('prtg_cas02', 'ヴァルキリーレルム 砦2', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('prtg_cas03', 'ヴァルキリーレルム 砦3', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('prtg_cas04', 'ヴァルキリーレルム 砦4', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('prtg_cas05', 'ヴァルキリーレルム 砦5', 1, 3, 0);
REPLACE INTO `pybot_map` VALUES('alde_alche', '錬金術師ギルド', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('in_rogue', 'ローグギルド', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_cru', 'クルセイダー転職試験場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_duncer', 'コモド小劇場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_monk', '聖カピトーリナ修道院', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_sage', 'セージ転職試験場', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('mag_dun01', 'ノーグロード 1層', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('mag_dun02', 'ノーグロード 2層', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('monk_test', '聖カピトーリナ修道院', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('quiz_test', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('yuno', 'シュバルツバルド共和国の首都ジュノー', 2, 1, 0);
REPLACE INTO `pybot_map` VALUES('yuno_fild01', 'ジュノーフィールド 01（国境検問所）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild02', 'ジュノーフィールド 02（キル・ハイルの別荘）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild03', 'ジュノーフィールド 03（エルメスプレート）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild04', 'ジュノーフィールド 04（エルメスプレート）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_in01', 'ジュノー 室内01', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('yuno_in02', 'ジュノー 室内02（セージキャッスル室内）', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('yuno_in03', 'ジュノー 室内03', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('yuno_in04', 'ジュノー 室内04（共和国図書館）', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('yuno_in05', 'ジュノー 室内05（ユミルの心臓動力室）', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('ama_dun01', 'アマツダンジョン 01（畳の迷宮）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('ama_dun02', 'アマツダンジョン 02（地下戦場跡）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('ama_dun03', 'アマツダンジョン 03（アマツ地下神社）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('ama_fild01', 'アマツフィールド 01', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('ama_in01', 'アマツ 室内01', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('ama_in02', 'アマツ 室内02（東湖城 泉水閣）', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('ama_test', 'モモタロ体験館', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('amatsu', '泉水の国アマツ', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('gon_dun01', 'コンロンダンジョン 01（西王母神殿）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('gon_dun02', 'コンロンダンジョン 02（神仙の碁盤）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('gon_dun03', 'コンロンダンジョン 03（武陵桃源）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('gon_fild01', 'コンロンフィールド 01', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('gon_in', 'コンロン 内部', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('gon_test', '格闘場', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('gonryun', '神仙の島コンロン', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('sec_in01', '検証用マップ1', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('sec_in02', '検証用マップ2', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('sec_pri', '調査用マップ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('umbala', 'ウータン族の村ウンバラ', 1, 1, 0);
REPLACE INTO `pybot_map` VALUES('um_dun01', 'ウンバラダンジョン 01（大樹の道）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('um_dun02', 'ウンバラダンジョン 02（深奥の密林）', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('um_fild01', 'ウンバラフィールド 01（ルルカ森）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('um_fild02', 'ウンバラフィールド 02（フムガ森）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('um_fild03', 'ウンバラフィールド 03（カララ沼）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('um_fild04', 'ウンバラフィールド 04（フムガジャングル）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('um_in', 'ウータン族の村ウンバラ 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('niflheim', '死者の街ニブルヘイム', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('nif_fild01', 'ニブルヘイムフィールド 01（秘境の村）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('nif_fild02', 'ニブルヘイムフィールド 02（ギョル渓谷）', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('nif_in', 'ニブルヘイム 室内', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('yggdrasil01', 'フベルゲルミルの泉(イグドラシルの幹)', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('valkyrie', 'ヴァルキリー神殿', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('himinn', 'ヴァルキリー神殿（ヒミン）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lou_in01', '龍之城 室内01', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('lou_in02', '龍之城 室内02', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('lou_dun03', '龍之城ダンジョン 03（白羊宮）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('lou_dun02', '龍之城ダンジョン 02（王陵 内部）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('lou_dun01', '龍之城ダンジョン 01（王陵）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('lou_fild01', '龍之城フィールド 01', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('louyang', '古都 龍之城', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('siege_test', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('n_castle', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('nguild_gef', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('nguild_prt', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('nguild_pay', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('nguild_alde', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('jawaii', '常夏の島 ジャワイ', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('jawaii_in', 'ジャワイ 室内', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('gefenia01', 'ゲフェニア 01', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gefenia02', 'ゲフェニア 02', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gefenia03', 'ゲフェニア 03', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('gefenia04', 'ゲフェニア 04', 1, 3, 1);
REPLACE INTO `pybot_map` VALUES('new_zone01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_zone02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_zone03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_zone04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('payon_in03', '山岳の都市フェイヨン 室内03', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('ayothaya', 'アユタヤ', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('ayo_in01', 'アユタヤ 室内01', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('ayo_in02', 'アユタヤ 室内02', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('ayo_fild01', 'アユタヤフィールド 01', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('ayo_fild02', 'アユタヤフィールド 02', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('ayo_dun01', 'アユタヤダンジョン 01（古代遺跡迷宮）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('ayo_dun02', 'アユタヤダンジョン 02（古代遺跡内部）', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('que_god01', '試練の場 01', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_god02', '試練の場 02', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('yuno_fild05', 'ジュノーフィールド 05（エルメスプレート）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild07', 'ジュノーフィールド 07（エルメス峡谷）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild08', 'ジュノーフィールド 08（キル・ハイル学院）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild09', 'ジュノーフィールド 09（シュバルツバルド警備隊野営地）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild11', 'ジュノーフィールド 11', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild12', 'ジュノーフィールド 12（国境検問所）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('alde_tt02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('turbo_n_1', 'ターボトラック競技場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('turbo_n_4', 'ターボトラック競技場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('turbo_n_8', 'ターボトラック競技場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('turbo_n_16', 'ターボトラック競技場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('turbo_e_4', 'ターボトラック競技場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('turbo_e_8', 'ターボトラック競技場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('turbo_e_16', 'ターボトラック競技場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('turbo_room', 'ターボトラック控え室', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('airplane', '飛行船（シュバルツバルド国内線）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('airport', '空港', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('einbech', '採鉱の村アインベフ', 2, 1, 0);
REPLACE INTO `pybot_map` VALUES('einbroch', '鋼鉄の都市アインブロック', 2, 1, 0);
REPLACE INTO `pybot_map` VALUES('ein_dun01', '鉱山ダンジョン 01', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('ein_dun02', '鉱山ダンジョン 02', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild06', 'アインブロックフィールド 06', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild07', 'アインブロックフィールド 07', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild08', 'アインブロックフィールド 08', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild09', 'アインブロックフィールド 09', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild10', 'アインブロックフィールド 10', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('ein_in01', 'アインブロック 室内01', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_sign01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_sign02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ein_fild03', 'アインブロックフィールド 03', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild04', 'アインブロックフィールド 04', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('lhz_fild02', 'リヒタルゼンフィールド 02(死神の峡谷)', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('lhz_fild03', 'リヒタルゼンフィールド 03', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_pre', 'シュバルツバルド政府庁舍', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_fild01', 'リヒタルゼンフィールド 01', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('lighthalzen', '企業都市リヒタルゼン', 2, 1, 0);
REPLACE INTO `pybot_map` VALUES('lhz_in01', 'レッケンベル本社', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_in02', 'リヒタルゼン 室内02', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_in03', 'リヒタルゼン 室内03', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_que01', 'リヒタルゼン 室内', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_dun01', '生体工学研究所 01', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('lhz_dun02', '生体工学研究所 02', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('lhz_dun03', '生体工学研究所 03', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('lhz_cube', 'キューブルーム', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('juperos_01', 'ジュピロス廃墟 01', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('juperos_02', 'ジュピロス廃墟 02', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('jupe_area1', 'ジュピロス保安区域 1', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('jupe_area2', 'ジュピロス保安区域 2', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('jupe_core', 'ジュピロス中心部', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('jupe_ele', 'ジュピロスエレベーター', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('jupe_ele_r', 'ジュピロスエレベーター室', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('jupe_gate', 'ジュピロス保安区域', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('y_airport', 'ジュノー空港', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_airport', 'リヒタルゼン空港', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('airplane_01', '飛行船（シュバルツバルド国外線）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('jupe_cave', 'ジュピロス洞窟入口', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('quiz_02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('hu_fild07', 'フィゲルフィールド 07', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('hu_fild05', 'フィゲルフィールド 05（アビスレイク）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('hu_fild04', 'フィゲルフィールド 04', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('hu_fild01', 'フィゲルフィールド 01（タナトスタワー）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild06', 'ジュノーフィールド 06（エルメスプレート）', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('job_soul', 'あなたの心', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_star', '太陽と月と星', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_job01', '秘密居酒屋', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_job02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_job03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('abyss_01', 'アビスレイク地下洞窟 01', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('abyss_02', 'アビスレイク地下洞窟 02', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('abyss_03', 'アビスレイク地下洞窟 03', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('thana_step', 'タナトスタワー上層部', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('thana_boss', 'タナトスタワー最上部', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('tha_scene01', 'タナトスタワー前', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('tha_t01', 'タナトスタワー下層部 01', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t02', 'タナトスタワー下層部 02', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t03', 'タナトスタワー下層部 03', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t04', 'タナトスタワー下層部 04', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t07', 'タナトスタワー上層部 07', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t05', 'タナトスタワー上層部 05', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t06', 'タナトスタワー上層部 06', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t08', 'タナトスタワー上層部 08', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t09', 'タナトスタワー上層部 09', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t10', 'タナトスタワー上層部 10', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t11', 'タナトスタワー上層部 11', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('tha_t12', 'タナトスタワー上層部 12', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('auction_01', '競売会場 01', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('auction_02', '競売会場 02', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('hugel', '田園都市フィゲル', 2, 1, 0);
REPLACE INTO `pybot_map` VALUES('hu_in01', 'フィゲル 室内01', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_bingo', 'ビンゴゲーム会場', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_hugel', 'オーディン神殿地下', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('p_track01', 'モンスターレース会場 01', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('p_track02', 'モンスターレース会場 02', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('odin_tem01', 'オーディン神殿 01', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('odin_tem02', 'オーディン神殿 02', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('odin_tem03', 'オーディン神殿 03', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('hu_fild02', 'フィゲルフィールド 02', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('hu_fild03', 'フィゲルフィールド 03', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('hu_fild06', 'フィゲルフィールド 06', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild01', 'アインブロックフィールド 01', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild02', 'アインブロックフィールド 02', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('ein_fild05', 'アインブロックフィールド 05', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('yuno_fild10', 'ジュノーフィールド 10', 2, 2, 1);
REPLACE INTO `pybot_map` VALUES('kh_kiehl02', 'キエルの部屋 02', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('kh_kiehl01', 'キエルの部屋 01', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('kh_dun02', '機械人形工場 B2F', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('kh_dun01', '機械人形工場 B1F', 2, 3, 1);
REPLACE INTO `pybot_map` VALUES('kh_mansion', 'キル・ハイル邸', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('kh_rossi', 'ロシミエル邸', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('kh_school', 'キル・ハイル学院内', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('kh_vila', 'キル・ハイルの別荘内', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_map1', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_map2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_map3', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_hunter', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_knight', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_priest', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_wizard', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ve_in02', 'ベインス 室内', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('rachel', 'アルナベルツ教国首都 ラヘル', 3, 1, 0);
REPLACE INTO `pybot_map` VALUES('ra_in01', 'ラヘル 室内01', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('ra_fild01', 'ラヘルフィールド 01（アウドムラ草原）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild02', 'ラヘルフィールド 02（オズ狭谷）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild03', 'ラヘルフィールド 03（イダ平原）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild04', 'ラヘルフィールド 04（アウドムラ草原）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild05', 'ラヘルフィールド 05（アウドムラ草原）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild06', 'ラヘルフィールド 06（ポルトルナ）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild07', 'ラヘルフィールド 07（オズ狭谷）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild08', 'ラヘルフィールド 08（イダ平原）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild09', 'ラヘルフィールド 09（アウドムラ草原）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild10', 'ラヘルフィールド 10（オズ狭谷）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild11', 'ラヘルフィールド 11（イダ平原）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild12', 'ラヘルフィールド 12（イダ平原）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_fild13', 'ラヘルフィールド 13（涙の海岸）', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ra_san01', 'フレイヤ大神殿聖域 01', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('ra_san02', 'フレイヤ大神殿聖域 02', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('ra_san03', 'フレイヤ大神殿聖域 03', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('ra_san04', 'フレイヤ大神殿聖域 04', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('ra_san05', 'フレイヤ大神殿聖域 05', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('ra_temin', 'フレイヤ大神殿 室内', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('ra_temple', 'フレイヤ大神殿（セスルムニル）', 3, 1, 0);
REPLACE INTO `pybot_map` VALUES('ra_temsky', '教皇執務室（空中庭園）', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_rachel', 'フレイヤ大神殿 室内', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('ice_dun01', '氷の洞窟 01', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('ice_dun02', '氷の洞窟 02', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('ice_dun03', '氷の洞窟 03', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('ice_dun04', '氷の洞窟 04', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_thor', 'トール火山ダンジョン', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('thor_camp', 'トール火山兵站基地', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('thor_v01', 'トール火山ダンジョン 01', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('thor_v02', 'トール火山ダンジョン 02', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('thor_v03', 'トール火山ダンジョン 03', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('veins', '峡谷都市ベインス', 3, 1, 0);
REPLACE INTO `pybot_map` VALUES('ve_in', 'ベインス 室内', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('ve_fild01', 'ベインスフィールド 01', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ve_fild02', 'ベインスフィールド 02', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ve_fild03', 'ベインスフィールド 03', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ve_fild04', 'ベインスフィールド 04', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ve_fild05', 'ベインスフィールド 05', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ve_fild06', 'ベインスフィールド 06', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('ve_fild07', 'ベインスフィールド 07', 3, 2, 1);
REPLACE INTO `pybot_map` VALUES('poring_c01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('poring_c02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_ng', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('nameless_i', '名もなき島 朝', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('nameless_n', '名もなき島 夜', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('nameless_in', '名もなき島 内部', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('abbey01', '修道院 01', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('abbey02', '修道院 02', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('abbey03', '修道院 03', 3, 3, 1);
REPLACE INTO `pybot_map` VALUES('poring_w01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('poring_w02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_san04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('moscovia', 'モスコビア', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('mosk_in', 'モスコビア 内部', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('mosk_ship', '船', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('mosk_fild01', 'クジラ島', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('mosk_fild02', 'モスコビアフィールド', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('mosk_dun01', '森', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('mosk_dun02', '深い森', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('mosk_dun03', '奥深い森', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('mosk_que', '？', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_4-1', 'タイムアタックモード 4-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('force_5-1', 'タイムアタックモード 5-1', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_r', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_05', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_06', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_07', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('06guild_08', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('z_agit', 'Z団のアジト', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_temsky', '教皇執務室（空中庭園）', 3, 0, 0);
REPLACE INTO `pybot_map` VALUES('itemmall', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bossnia_01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bossnia_02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bossnia_03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bossnia_04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('schg_cas01', 'ニダヴェリール 砦1', 2, 3, 0);
REPLACE INTO `pybot_map` VALUES('schg_cas02', 'ニダヴェリール 砦2', 2, 3, 0);
REPLACE INTO `pybot_map` VALUES('schg_cas03', 'ニダヴェリール 砦3', 2, 3, 0);
REPLACE INTO `pybot_map` VALUES('schg_cas04', 'ニダヴェリール 砦4', 2, 3, 0);
REPLACE INTO `pybot_map` VALUES('schg_cas05', 'ニダヴェリール 砦5', 2, 3, 0);
REPLACE INTO `pybot_map` VALUES('sch_gld', 'ニダヴェリール', 2, 1, 0);
REPLACE INTO `pybot_map` VALUES('cave', '洞窟の村', 2, 1, 0);
REPLACE INTO `pybot_map` VALUES('moc_fild20', '次元の狭間 01', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild21', '次元の狭間 02', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild22', '次元の狭間 03', 1, 2, 1);
REPLACE INTO `pybot_map` VALUES('que_ba', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_moc_16', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_moon', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('arug_cas01', 'ヴァルフレイヤ 砦1', 3, 3, 0);
REPLACE INTO `pybot_map` VALUES('arug_cas02', 'ヴァルフレイヤ 砦2', 3, 3, 0);
REPLACE INTO `pybot_map` VALUES('arug_cas03', 'ヴァルフレイヤ 砦3', 3, 3, 0);
REPLACE INTO `pybot_map` VALUES('arug_cas04', 'ヴァルフレイヤ 砦4', 3, 3, 0);
REPLACE INTO `pybot_map` VALUES('arug_cas05', 'ヴァルフレイヤ 砦5', 3, 3, 0);
REPLACE INTO `pybot_map` VALUES('aru_gld', 'ヴァルフレイヤ', 3, 1, 0);
REPLACE INTO `pybot_map` VALUES('bat_room', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bat_a01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bat_a02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bat_b01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bat_b02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qsch01', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qsch02', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qsch03', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qsch04', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qsch05', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qaru01', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qaru02', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qaru03', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qaru04', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_qaru05', '虚像のオーコルニル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@cata', '封印された神殿（墓地）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@cata', '封印された神殿（大封印祭壇）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('e_tower', 'ミスティーアイランド', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@tower', 'エンドレスタワー 1層（1～25F）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@tower', 'エンドレスタワー 2層（26～50F）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('3@tower', 'エンドレスタワー 3層（51～75F）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('4@tower', 'エンドレスタワー 4層（76～99F）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('5@tower', 'エンドレスタワー 5層（100F）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('6@tower', 'エンドレスタワー 覇王の間', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('mid_camp', 'ミッドガルド連合軍駐屯地', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('mid_campin', 'ミッドガルド連合軍駐屯地内部', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('man_fild01', 'マヌクフィールド 01', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('man_fild03', 'マヌクフィールド 03', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('spl_fild02', 'スプレンディッドフィールド 02', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('spl_fild03', 'スプレンディッドフィールド 03', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('moc_fild22b', '時空の裂け目', 1, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_dan01', 'フィゲルフィールド', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_dan02', 'ジュノーの捨てられた家内部', 2, 0, 0);
REPLACE INTO `pybot_map` VALUES('schg_que01', 'モアストーンの草原', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('schg_dun01', 'ギルドダンジョン シュバルツバルド', 2, 3, 0);
REPLACE INTO `pybot_map` VALUES('arug_que01', 'モアストーンの草原', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('arug_dun01', 'ギルドダンジョン アルナベルツ', 3, 3, 0);
REPLACE INTO `pybot_map` VALUES('1@orcs', 'オーク地下洞窟 01（過去）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@orcs', 'オーク地下洞窟 02（過去）', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@nyd', 'ニーズヘッグの巣', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@nyd', 'ニーズヘッグの巣', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('nyd_dun01', 'イグドラシル中心部 01', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('nyd_dun02', 'イグドラシル中心部 02', 4, 3, 0);
REPLACE INTO `pybot_map` VALUES('manuk', '鉱山の街 マヌク', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('man_fild02', 'マヌクフィールド 02', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('man_in01', 'マヌク 内部', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('splendide', '前線基地 スプレンディッド', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('spl_fild01', 'スプレンディッドフィールド 01', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('spl_in01', 'スプレンディッド 内部01', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('spl_in02', 'スプレンディッド 内部02', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('bat_c01', 'クリーガーフォンミッドガルド', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bat_c02', 'クリーガーフォンミッドガルド', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bat_c03', 'クリーガーフォンミッドガルド', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_para01', '楽園団 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_arch01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_arch02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_arch03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_guil01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_guil02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_guil03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_rang01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_rang02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_rune01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_rune02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_rune03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_war01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_war02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('jupe_core2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('brasilis', 'ブラジリス', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('bra_in01', 'ブラジリス 室内', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('bra_fild01', 'ブラジリスフィールド 01', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('bra_dun01', '滝の中の洞窟 01', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('bra_dun02', '滝の中の洞窟 02', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('dicastes01', 'サファ族の首都 エルディカスティス', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('dicastes02', 'ブルーメヴァルト', 4, 1, 0);
REPLACE INTO `pybot_map` VALUES('dic_in01', 'エルディカスティス 室内', 4, 0, 0);
REPLACE INTO `pybot_map` VALUES('dic_fild01', 'カミダル山麓 01', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('dic_fild02', 'カミダル山麓 02', 4, 2, 1);
REPLACE INTO `pybot_map` VALUES('dic_dun01', 'カミダルトンネル', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('dic_dun02', 'スカラバホール', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('job3_gen01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('s_atelier', '影の工房', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job3_sha01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('mora', 'レシア族の街 モーラ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bif_fild01', 'ビフロスト 南部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('bif_fild02', 'ビフロスト 北部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@mist', '霧の森', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('dewata', 'デワタ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('dew_in01', 'デワタ 室内', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('dew_fild01', 'デワタフィールド 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('dew_dun01', 'クラカト火山', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('dew_dun02', 'イスタナ洞窟', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_house_s', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('malangdo', 'マラン島', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('mal_in01', 'マラン島 室内', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('mal_in02', 'ナビ号 船内', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('mal_dun01', '星明りの珊瑚礁', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@pump', '地下排水路', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@pump', '地下排水路 最奥部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@cash', '暴窟王の洞窟', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_dun05', 'イズルード海底都市', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('evt_mobroom', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('alde_tt03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('dic_dun03', 'スカラバガーデン', 4, 3, 1);
REPLACE INTO `pybot_map` VALUES('1@lhz', '禁忌の研究所', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_dun04', '生体工学研究所 04', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_lhz', '生体工学研究所', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('evt_swar_b', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('evt_swar_r', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('evt_swar_s', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('evt_swar_t', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gld2_ald', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gld2_gef', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gld2_pay', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gld2_prt', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gld_dun01_2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gld_dun02_2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gld_dun03_2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gld_dun04_2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('malaya', 'ポートマラヤ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_ko', '隠された場所', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_scene01', 'バコナワ湖', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@ma_b', 'バコナワの棲み処', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@ma_c', 'ブワヤの巣', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@ma_h', '闇のビョンウンゴ病院2階', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_in01', '室内', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_dun01', 'ビョンウンゴ病院1階', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_fild01', 'バリオ・マヒワガ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_fild02', 'バリオ・フォレスト', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif01', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif02', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif03', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif04', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif05', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif06', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif07', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif08', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ma_zif09', 'ジプニー 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('new_event', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('eclage', 'ラフィネ族の首都 エクラージュ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_fild01', '花が咲き始めた大地', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_tdun01', 'ビフロストタワー 1階', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_tdun02', 'ビフロストタワー 2階', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_tdun03', 'ビフロストタワー 3階', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_tdun04', 'ビフロストタワー 4階', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_avan01', 'エイヴァント研究室', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@ecl', 'エクラージュ 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_in01', 'エクラージュ 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_in02', 'エクラージュ 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_in03', 'エクラージュ 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_in04', 'エクラージュ 内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ecl_hub01', 'エクラージュ通路', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_prydn1', 'ピラミッドダンジョン 秘密の地下室01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('moc_prydn2', 'ピラミッドダンジョン 秘密の地下室02', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('treasure_n1', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('treasure_n2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_int', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ng01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_int01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_int02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_int03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_int04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac01_a', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac02_a', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac01_b', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac02_b', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac01_c', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac02_c', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac01_d', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('iz_ac02_d', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_prtcas01', 'ゲオルグ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_prtcas02', 'リハルト ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_prtcas03', 'ウィグナー', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_prtcas04', 'ハイネン', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_prtcas05', 'ネリウス', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_aldecas1', 'グラリス', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_aldecas2', 'ディフォルテー', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_aldecas3', 'ソリン', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_aldecas4', 'ビニット', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_aldecas5', 'Ｗ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_fild08a', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_fild08b', 'プロンテラフィールド 08(夕暮れ時)', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_fild08c', 'プロンテラフィールド 08(丑三つ時)', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_fild08d', 'プロンテラフィールド 08(夜明け前)', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('izlude_a', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('izlude_b', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('izlude_c', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('izlude_d', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_prt_gld', 'グロリア', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('te_alde_gld', 'カプラガーデン', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('teg_dun01', 'ギルドダンジョン グロリア', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('teg_dun02', 'ギルドダンジョン カプラガーデン', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@gl_k', '古の騎士団01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@gl_k', '古の騎士団02', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gl_chyard_', '悪夢のグラストヘイムカタコンベ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gl_cas02_', '悪夢のグラストヘイム古城2F', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('evt_bomb', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@def01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@def02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@def03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@gef', 'ゲフェン魔法大会', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@face', 'フェイスワームの巣', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@sara', 'サラの記憶', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@gef_in', 'ゲフェン魔法大会', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('dali', '次元の狭間 時の通路01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('dali02', '次元の狭間 時の通路02', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@ge_st', 'ゲフェン魔法大会', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@spa', '亡霊の王宮', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@tnm1', '魔神の塔上層', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@tnm2', '魔神の塔最上階', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@tnm3', 'モロク城地下', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@dth1', 'ビオスの島 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@dth2', 'ビオスの島 02', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@dth3', 'ビオスの島 03', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@eom', '魔神殿', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@jtb', '悪夢のジターバグ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@rev', 'モルスの洞窟', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@xm_d', 'ホラーおもちゃ工場', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('moro_cav', 'フレイムケイブ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('moro_vol', 'フレイムヴァレー', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('silk_lair', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('c_tower2_', '捻じれた時間の時計塔地上 2F', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('c_tower3_', '捻じれた時間の時計塔地上 3F', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@mcd', 'チャールストン工場', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ver_eju', 'ジュピロス東側', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ver_tunn', 'ウェルス外郭トンネル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('verus03', 'ウェルス中央広場', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('verus04', 'ウェルス発掘地', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('job_gun', 'リベリオン転職所', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@air1', '飛行船', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@air2', '飛行船', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@glast', '過去のグラストヘイム', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_dun_n', '戦死者の墓', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lhz_d_n2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@gl_kh', '古の騎士団01(ハード)', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@gl_kh', '古の騎士団02(ハード)', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@lab', '中央実験室', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@uns', '最後の部屋', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('un_bk_q', '地下シェルター(メモリーレコード)', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('un_bunker', '地下シェルター', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('un_myst', '地下トンネル', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('verus01', '実験棟-OPTATIO', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('verus02', '研究棟-WISH', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('paramk', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@infi', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@ffp', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@mir', '過去の儀式の間', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@mir', '儀式の間', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@sthb', '空中要塞内部', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@sthc', '空中要塞秘密の部屋', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@sthd', '空中要塞最上階', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_cas', 'プロンテラ中央宮', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_cas_q', 'プロンテラ離宮', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_prison', 'プロンテラ地下監獄', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_lib', '王家の記憶の間', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_lib_q', '過去の王家の記憶の間', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_q', '侵攻されたプロンテラ(避難地)', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_pri00', 'プロンテラ監獄', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('int_land', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('int_land01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('int_land02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('int_land03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('int_land04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasagna', '港町ラザーニャ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasa_fild01', 'ラビオル平原 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasa_fild02', 'ラビオル森 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasa_dun01', '龍の巣 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasa_dun02', '龍の巣 02', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasa_dun03', '龍の巣 03', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('conch_in', 'コンキリエ号', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasa_in01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasa_dun_q', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@pop1', '真昼の弦月 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@pop2', '真昼の弦月 02', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@pop3', '真昼の弦月 03', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@slw', 'ヴェルナー研究所中央室', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@swat', 'ハートハンター軍事基地(外郭)', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('que_swat', 'ハートハンター軍事基地', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('slabw01', 'ヴェルナー研究所 A棟', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('rebel_in', 'クラナネミエリー', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@md_gef', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@md_pay', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('har_in01', 'ロックリッジ室内', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('harboro1', 'ロックリッジ', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('harboro2', 'ロックリッジ地下街', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('rockmi1', 'ロックリッジ鉱山 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('rockmi2', 'ロックリッジ鉱山 02', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('rockrdg1', 'キワワ砂漠 01', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('rockrdg2', 'キワワ砂漠 02', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@gl_k2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2@gl_k2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@xm_d2', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('pay_d03_i', '月夜花の悪夢', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('gef_d01_i', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ice_d03_i', 'フローズンメモリー', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@tre', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@begi', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('tur_d03_i', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('tur_d04_i', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@crd', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ordeal_a00', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ordeal_a02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('pprontera', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('niflxmas', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('sch_lab', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('nakhyang', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('lasa_sea', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@drdo', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('x_lhz', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('x_prt', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('x_ra', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('prt_evt_in', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('vis_h01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('vis_h02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('vis_h03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('vis_h04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('ein_d02_i', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('com_d02_i', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('1@soul', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('star_frst', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('star_in', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_05', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_06', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_07', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_08', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2009rwc_f01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2012rwc_01', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2012rwc_02', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2012rwc_03', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2012rwc_04', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2012rwc_05', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2012rwc_06', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2012rwc_07', '？', 0, 0, 0);
REPLACE INTO `pybot_map` VALUES('2012rwc_08', '？', 0, 0, 0);
